petstagram/accounts/urls.py
from django.urls import path, include

from petstagram.accounts import views

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),  # new
    path('profile/<int:pk>/', include([
        path('', views.UserDetailsView.as_view(), name='profile-details'),
        path('edit/', views.UserEditView.as_view(), name='profile-edit'),
        path('delete/', views.UserDeleteView.as_view(), name='profile-delete'),
    ])),
]

petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.common.urls')),
    path('accounts/', include('petstagram.accounts.urls')),
    path('pets/', include('petstagram.pets.urls')),
    path('photos/', include('petstagram.photos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/accounts/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.contrib.auth.models import AbstractUser

from petstagram.accounts.validators import validate_isalpha


class PetstagramUser(AbstractUser):
    MALE = 'Male'
    FEMALE = 'Female'
    DO_NOT_SHOW = 'Do not show'

    GENDERS = [(x, x) for x in (MALE, FEMALE, DO_NOT_SHOW)]

    email = models.EmailField(unique=True)
    first_name = models.CharField(
        max_length=30,
        validators=(MinLengthValidator(2), validate_isalpha),
        null=True,
        blank=True)

    last_name = models.CharField(
        max_length=30,
        validators=(MinLengthValidator(2), validate_isalpha),
        null=True,
        blank=True)

    profile_picture = models.URLField(null=True, blank=True)

    gender = models.CharField(
        max_length=11,
        choices=GENDERS,
        null=True,
        blank=True,
        default=DO_NOT_SHOW
    )

    def get_user_first_last_names(self):
        if self.first_name and self.last_name:
            return self.first_name + ' ' + self.last_name
        elif self.first_name or self.last_name:
            return self.first_name or self.last_name

    def get_user_name(self):
        result = self.get_user_first_last_names()
        if result:
            return result
        else:
            return self.username




petstagram/pets/models.py
from django.db import models
from django.template.defaultfilters import slugify

from petstagram.accounts.models import PetstagramUser


class Pet(models.Model):
    name = models.CharField(max_length=30)
    personal_photo = models.URLField()
    date_of_birth = models.DateField(blank=True, null=True)
    slug = models.SlugField(unique=True, editable=False)
    user = models.ForeignKey(to=PetstagramUser, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f"{self.name}-{self.id}")
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

petstagram/photos/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from petstagram.accounts.models import PetstagramUser
from petstagram.pets.models import Pet
from petstagram.photos.validators import validate_file_size


class Photo(models.Model):
    photo = models.ImageField(upload_to='images', validators=(validate_file_size,))
    description = models.TextField(max_length=300, validators=(MinLengthValidator(10),), blank=True, null=True)
    location = models.CharField(max_length=30, blank=True, null=True)
    tagged_pets = models.ManyToManyField(Pet, blank=True)
    date_of_publication = models.DateField(auto_now=True)
    user = models.ForeignKey(to=PetstagramUser, on_delete=models.CASCADE)

petstagram/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField

from petstagram.accounts.models import PetstagramUser


class PetstagramUserCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = PetstagramUser
        fields = ('username', 'email')


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True, "placeholder": "Username"}))
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", "placeholder": "Password"}),
    )


class PetstagramUserEditForm(forms.ModelForm):
    class Meta():
        model = PetstagramUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture', 'gender')
        exclude = ('password',)
        labels = {'username': 'Username',
                  'first_name': 'First Name:',
                  'last_name': 'Last Name:',
                  'email': 'Email:',
                  'profile_picture': 'Image:',
                  'gender': 'Gender:'
                  }

petstagram/accounts/views.py
from django.urls import reverse_lazy
from django.views import generic as views
from django.contrib.auth import views as auth_views

from petstagram.accounts.forms import PetstagramUserCreateForm, LoginForm, PetstagramUserEditForm
from petstagram.accounts.models import PetstagramUser


class UserRegisterView(views.CreateView):
    model = PetstagramUser
    form_class = PetstagramUserCreateForm
    template_name = 'accounts/register-page.html'
    success_url = reverse_lazy('login')


class UserLoginView(auth_views.LoginView):
    form_class = LoginForm
    template_name = 'accounts/login-page.html'
    next_page = reverse_lazy('home')


class UserLogoutView(auth_views.LogoutView):
    next_page = reverse_lazy('login')


class UserEditView(views.UpdateView):
    model = PetstagramUser
    form_class = PetstagramUserEditForm
    template_name = 'accounts/profile-edit-page.html'

    def get_success_url(self):
        return reverse_lazy('profile-details', kwargs={'pk': self.object.pk})


class UserDetailsView(views.DetailView):
    model = PetstagramUser
    template_name = 'accounts/profile-details-page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_likes_count = sum(p.like_set.count() for p in self.object.photo_set.all())

        context.update({
            'total_likes_count': total_likes_count,
        })

        return context


class UserDeleteView(views.DeleteView):
    model = PetstagramUser
    template_name = 'accounts/profile-delete-page.html'
    success_url = reverse_lazy('home')

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user.delete()
        return super().post(request, *args, **kwargs)


templates/accounts/email-greeting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Petstagram</title>
</head>
<body style="display: flex;
			justify-content: center;">
<div style="display: flex;
			justify-content: center;
			border: 3px solid rgb(65, 63, 63);
			border-radius: 20px;
			margin: 2%;
			max-width: 620px;">
    <div>
		<table>
			<nav style="">
		<img style="width: 10rem;
			 margin-top: 10px;
			 margin-left: -4px;
			 height: 3.3rem;"
			 src="https://jdzejo.stripocdn.email/content/guids/3be6ad80-cf0f-461f-807a-b499c494e798/images/screenshot_1_roO.png"
			 alt="Logo">
	</nav>
		</table>

        <h1 style="			text-align: center;
                color: rgb(65, 63, 63);
                font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">

            <!-- Receiver username -->
            Hello, username !</h1>

        <div style="display: flex;
                justify-content: center;">
            <img style="width: 70%;
            display: block;
            margin-left: auto;
            margin-right: auto;"
                 id="cat-image"
                 src="https://jdzejo.stripocdn.email/content/guids/CABINET_b71dddfca1f6a4c91ed66e0fc480ad7f/images/ezgifcomgifmaker.gif"
                 alt="gif cat">
        </div>

        <p style="max-width: 620px;
            padding: 20px 20px 0 20px;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
            Congratulations on creating your profile at Petstagram.
            Our pets are our best friends, and we love them so much that we want to share every moment with them with
            the
            world.
            Let's make the biggest pet community!
        </p>
        <p style="max-width: 620px;
            padding: 20px 20px 0 20px;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
            Sincerely,
            <br>
            <img style="width: 30%;
            margin-top: 10px;
            margin-left: -4px;"
                 src="https://jdzejo.stripocdn.email/content/guids/3be6ad80-cf0f-461f-807a-b499c494e798/images/screenshot_1_roO.png"
                 alt="Logo">
        </p>
    </div>
</div>
</body>
</html>

templates/accounts/login-page.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}
    <!-- Start Login Section-->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Login Form-->
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <!-- Login Button-->
                <button type="submit">Log in</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="second-option">

            <!-- Link to Register Page-->
            <p>Don't have account? <a href="{% url 'register' %}">Register</a></p>
        </div>
    </div>
    <!-- End Login Section-->

{% endblock %}

templates/accounts/profile-delete-page.html
{% extends 'base.html' %}

{% block content %}
    <!-- Start Delete Profile Section -->
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <form method="post" action="{% url 'profile-delete' request.user.pk %}">
                {% csrf_token %}
            <div class="sure-buttons">
                <!-- Yes (Delete Profile) Button -->
                <button>Yes</button>
                <!-- Go Back Button -->
                <a class="edit-btn" href="javascript:history.back()">Go Back</a>
            </div>
            </form>
            <img src="/images/are_you_sure_cat.gif" alt="are you sure cat git">
        </div>
    <!-- End Delete Profile Section -->

{% endblock %}

templates/accounts/profile-details-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Start Profile Details Section -->
    <div class="profile">

        <!-- Start Profile Personal Data Section -->
        <div class="profile-data">
            <div class="profile_img">
                <div class="image">

                    <!-- Profile Image -->
                    {% if petstagramuser.profile_picture %}
                        <img src="{{ petstagramuser.profile_picture }}" alt="img8">
                    {% else %}
                        <img src="{% static 'images/person.png' %}" alt="img8">
                    {% endif %}
                </div>
            </div>
            <div class="personal">
                <div class="edit">
                    <!-- User Username -->
                    <p>{{ petstagramuser.username }}</p>

                    <!-- IF the viewer is the owner of the profile -->
                    {% if petstagramuser == request.user %}
                        <!-- Link to Edit Profile Page -->
                        <a href="{% url 'profile-edit' petstagramuser.pk %}">
                            <img class="edit-img" src='{% static 'images/edit-pen-icon-6.jpg' %}' alt="edit button">
                        </a>

                        <!-- Link to Delete Profile Page -->
                        <a href="{% url 'profile-delete' petstagramuser.pk %}">
                            <img class="bin-img" src="{% static 'images/icon-remove-22.jpg' %}" alt="bin button">
                        </a>
                        <!-- End IF the viewer is the owner of the profile -->
                    {% endif %}
                </div>
                <div class="data">

                    <!-- Total Number of Photos by the User -->
                    <span>{{ petstagramuser.photo_set.count }}</span>
                    <p>photos</p>

                    <!-- Total Number of Pets owned by the User -->
                    <span>{{ petstagramuser.pet_set.count }}</span>
                    <p>pets</p>

                    <!-- Total Number of Likes for the User -->
                    <span>{{ total_likes_count }}</span>
                    <p>likes</p>
                </div>
                <!-- User First and Last Name IF Added -->
                {% if petstagramuser.first_name or petstagramuser.last_name %}
                    <h3 class="names">{{ petstagramuser.get_user_first_last_names }}</h3>
                {% endif %}
                <!-- User Email Address -->
                <p class="email">{{ petstagramuser.email }}</p>

                <!-- User Gender IF Added -->
                {% if petstagramuser.gender != "Do not show" %}
                    <p class="gender">{{ petstagramuser.gender }}</p>
                {% endif %}
            </div>
        </div>
        <!-- End Profile Personal Data Section -->

        <!-- Start Pets Data Section -->
        <div class="pets">
            <div class="statuses">
                {% for pet in petstagramuser.pet_set.all %}
                    <!-- Start 1st Pet Details Page -->
                    <!-- Link to First Pet Details Page -->
                    <a href="{% url 'pet-details' petstagramuser.username pet.slug %}">
                        <div class="head-pet">
                            <div class="status">
                                <div class="image">
                                    <!-- Pet Image -->
                                    <img src="{{ pet.personal_photo }}"
                                         alt="pet img">
                                </div>
                            </div>
                            <!-- Pet Name -->
                            <p>{{ pet.name }}</p>
                        </div>
                    </a>
                    <!-- End 1st Pet Details Page -->
                {% endfor %}
            </div>
        </div>
        <!-- End Pets Data Section -->

        <!-- Start Last Uploaded Photos Section -->
        <div class="pet-photos">

            <!-- Link to Last Uploaded Pet Photo -->
            {% for photo in page_obj.object_list %}
                <a href="{% url 'photo-details' photo.id %}">
                    <!-- Pet Photo -->
                    <img src="{{ photo.photo.url }}"
                         alt="pet img">
                </a>
            {% endfor %}
            <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
            </div>
        </div>

        <!-- End Last Uploaded Photos Section -->

    </div>
    <!-- End Profile Details Section -->

{% endblock %}

templates/accounts/profile-edit-page.html
{% extends 'base.html' %}

{% block content %}
    <!-- Start Edit Profile Section -->
    <div class="edit-delete">
        <h2>Edit Profile</h2>
        <!-- Start Edit Profile From -->
        <form method="post">
            {% csrf_token %}

            {% for field in form %}
                <p class="error"> {{ field.errors }} </p>
                <div class="label-input">
                    <label>{{ field.label }}</label>

                    {% if not field.label == "Gender:" %}
                        {{ field }}

                    {% else %}
                        <div class="list-choice">
                            <div class="list-choice-title">Gender</div>
                            <div class="list-choice-objects">

                                {% for type, value in form.fields.gender.choices %}
                                    <label>
                                        <input type="radio" value="{{ value }}" name="gender"
                                                {% if form.gender.value == value %}
                                               checked
                                                {% endif %}/>
                                        <span>{{ value }}</span>
                                    </label>
                                {% endfor %}

                            </div>
                        </div>
                    {% endif %}

                </div>
                <br>
            {% endfor %}

            <!-- Edit Profile Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Profile Form -->
    </div>
    <!-- End Edit Profile Section -->
{% endblock %}

templates/accounts/register-page.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}
    <!-- Start Register Section -->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Register Form -->
            <form method="post">
                {% csrf_token %}

                {{ form.username.errors }}
                {{ form.username|placeholder:'Username' }}
                {{ form.email.errors }}
                {{ form.email|placeholder:'Email' }}
                {{ form.password1.errors }}
                {{ form.password2.errors }}
                {{ form.password1|placeholder:'Password' }}
                {{ form.password2|placeholder:'Repeat password' }}
                <!-- Register Button -->
                <button type="submit">Register</button>
            </form>
            <!-- End Register Form -->

        </div>
        <div class="second-option">

            <!-- Link to Login Page -->
            <p>Have an account? <a href="{% url 'login' %}">Log in</a></p>
        </div>
    </div>
    <!-- End Register Section -->

{% endblock %}